module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false,
  theme: {
    colors: {
      "blue-light": "#8382FFa",
      blue: "#3633FF",
      "blue-dark": "#100EE2",
      red: "#E90C59",
      yellow: "#FEFF00",
      purple: "#7A52FF",
      black: "#01001F",
      white: "#fff",
      "white-blue": "#F0F0FF",
      gray: "#747380",
      "gray-faint": "#fdfdfd",
      "gray-light": "#92929B",
      "gray-lightish": "#DBDBE7",
      "gray-lighter": "#EAEAF1",
      "gray-lightest": "#F4F4F7",
      gold: "#A4882D",
    },
    fontSize: {
      xs: ["11px", "16px"],
      sm: ["12px", "16px"],
      13: ["13px", "20px"],
      md: ["15px", "24px"],
      base: ["16px", "24px"],
      18: ["18px", "28px"],
      22: ["22px", "28px"],
      26: ["26px", "32px"],
      "5xl": ["45px", "52px"],
      "6xl": ["54px", "60px"],
      "7xl": ["65px", "72px"],
    },
    extend: {
      boxShadow: {
        inset: "0 -1px 0 0 rgba(0, 0, 0, 0.055)",
      },
    },
  },
  variants: {
    textColor: ["hover", "group-hover", "visited"],
    backgroundColor: ["hover", "group-hover"],
    borderColor: ["hover", "group-hover", "focus"],
    scale: ["active"],
  },
  plugins: [],
};
